[tool.poetry]
name = "BeatPrints-Open"
version = "1.1.6.post1"
description = "Create Pinterest-style music posters with open metadata providers."
authors = ["elysianmyst <74355265+TrueMyst@users.noreply.github.com>"]
license = "CC-BY-NC-SA-4.0"
readme = "README.md"

keywords = ["music", "lyrics", "pinterest", "lrclibapi", "itunes", "deezer"]
repository = "https://github.com/pommotion/BeatPrints-Open"

packages = [{ include = "BeatPrints" }, { include = "cli" }]

[tool.poetry.dependencies]
python = "^3.12"
requests = "*"
pylette = "*"
pillow = "*"
lrclibapi = "*"
fonttools = "*"
questionary = "*"
rich = "*"
toml = "*"
qrcode = "*"

[tool.poetry.scripts]
beatprints = 'cli.prompt:main'

[tool.poetry.group.dev.dependencies]
black = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
